### ISSUE TITLE
add mricron

### ISSUE THREAD

**Issue by stebo85** [NeuroDesk/neurocontainers#103]
https://github.com/neurolabusc/MRIcron/releases

**Comment by TomEmotion** [comment]
I take it this to cater to users who can't use MRIcroGL due to graphics acceleration requirements?
Would it make sense to package MRIcron within the MRIcroGL container?

Regardless, happy to have a stab at creating this as part of my container creation learning experience (currently creating some electrophys viewers).

**Comment by stebo85** [comment]
MRIcroGL runs really well even without graphics acceleration :) But a user at CAI requested mricron because it still has some nice features although discontinued. Our IT team at CAI wanted to tackle this container as a practice session tomorrow and I am not sure if they started already. Would you like to wait a few days until I know or maybe there is another tool that you know well and is still missing?

**Comment by TomEmotion** [comment]
Sure, no problem.

**Comment by stebo85** [comment]
Done by CAI IT @ahockings
