### ISSUE TITLE
Add vmtk

### ISSUE THREAD

**Issue by SaskiaBollmann** [NeuroDesk/neurocontainers#332]

**Comment by Vbitz** [comment]
@stebo85 VMTK is interesting since it's officially distributed via Anaconda. Could this be a license issue for us?

**Comment by stebo85** [comment]
yes, I would prefer if we can build from source or get it from conda-forge instead

**Comment by Vbitz** [comment]
Building from source seemed easy enough with the superbuild but the build process takes ages.

The issue is it needs to build ITK and VTK from source as well.

I tried the versions in the Ubuntu repos but they failed with a compiler error (and the superbuild doesn't work in that case since it tries to wrap Java which doesn't seem to work on VTK 9).

I'll probably commit a container using the superbuild but I'll try to get a better version working first since the superbuild takes about 2 hours.

**Comment by Vbitz** [comment]
Seems the different builds are broken.

I got it building using Ubuntu Noble but most of the commands don't work since it needs libraries which are not built for some reason.

I got it to work using Miniforge which seems like the best approach. That's using entirely conda-forge.

I'll commit a very simple container that just installs it with conda-forge.

**Comment by stebo85** [comment]
@SaskiaBollmann - vmtk is now available on neurodesk - can you test?
