### ISSUE TITLE
Add latest FSL release

### ISSUE THREAD

**Issue by hanayik** [NeuroDesk/neurocontainers#411]
@stebo85 or @astewartau , what are the necessary steps to add the latest FSL release to Neurodesk? I'm happy to take a stab at doing this if you can point me in the right direction.

**Comment by stebo85** [comment]
Dear @hanayik,

Updating FSL to the latest version in Neurodesk would only involve to increase the version number here: https://github.com/NeuroDesk/neurocontainers/blob/03bb7e8dd6eb45c6ae400541b9c4bd3d2df12d6a/recipes/fsl/build.sh#L5

Since we use Neurodocker to build our containers, this will work out-of-the-box if Neurodocker also updated their recipes (https://github.com/ReproNim/neurodocker/blob/master/neurodocker/templates/fsl.yaml), which they did already as it seems :) 

Thank you
Steffen

**Comment by stebo85** [comment]
Dear @hanayik ,

I updated FSL to version to 6.0.7.1 and I also added a fix for the missing GUIs. The problem was that these GUIs are softlinks to a Runtcl that then replaces the name and these were not identified as valid binaries from our script. I just need to do one more little fix and then it's good to go for testing :)

Thank you
Steffen

**Comment by stebo85** [comment]
Dear @hanayik,

I updated fsl to the latest version (6.0.7.1) and we released a new version of Neurodesk. The GUIs are all working since 6.0.6.4 and the new versions are now available in the cloud versions of Neurodesk (https://www.neurodesk.org/docs/getting-started/neurodesktop/play/) and the local versions.

<img width="2791" alt="image" src="https://github.com/NeuroDesk/neurocontainers/assets/4021595/40605b1b-0c46-41cb-be56-ac7c89931e55">


Could you test it and let me know if you see anything else that's needed?

Thank you
Steffen

**Comment by hanayik** [comment]
@stebo85 , it looks (and works) great with the latest FSL. Thanks! NiiVue also works in firefox (which was a welcome surprise) 😀
