### ISSUE TITLE
Automatic UPDATE 

### ISSUE THREAD

**Issue by karl-koschutnig** [NeuroDesk/neurocontainers#847]
Hello, 
I have a very global question. 
There is so much dynamic in updated containers in the Neurodesk environment that we must click the UPDATE button to get the newest versions of the prepared containers whenever we start Neurodesk. It's not a big deal; it's just a little inconvenient.

Would it be possible to make a auto-update while starting the Neurodesk application, that would help a lot. 

Cheers, Karl

**Comment by stebo85** [comment]
Dear @karl-koschutnig,

we removed the auto-update on startup a while ago, because we implemented two reproducible solutions for this problem :)

1) You can start any tool version from the command line in Neurodeskdesktop (even if it's not in the menu yet!) by explicitly loading the tool version using `module load toolname/version` (or short ml)
Here is an example:
<img width="2543" alt="image" src="https://github.com/user-attachments/assets/7538482f-324e-49f0-b6e3-fc28942c4c2d">

2) If you start Neurodesktop from the command line, you can start any of the github tags and they will start a desktop with all tools available through the menu system at build time:
<img width="586" alt="image" src="https://github.com/user-attachments/assets/8cb27e13-30a2-4451-9c47-be5627573244">
So, for example:
```
docker volume create neurodesk-home &&
sudo docker run \
  --shm-size=1gb -it --privileged --user=root --name neurodesktop \
  -v ~/neurodesktop-storage:/neurodesktop-storage \
  --mount source=neurodesk-home,target=/home/jovyan \
  -e NB_UID="$(id -u)" -e NB_GID="$(id -g)" \
  -p 8888:8888 \
  -e NEURODESKTOP_VERSION=2024-10-16 vnmd/neurodesktop:2024-10-16
```

We will also update the version distributed through the Neurodeskapp in the next days :)

Does this help?
